"""Government scheme discovery and eligibility (PostgreSQL + rules)."""

# from app.config.database import SessionLocal
# from app.models.db import ...

# def get_eligible_schemes(age: int, income: float, state: str, occupation: str) -> list: ...
# def search_schemes(query: str) -> list: ...
